# Generated by Django 3.1.3 on 2020-11-09 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFactorVerification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True, verbose_name='secret key')),
                ('code', models.CharField(blank=True, help_text='You must enter the code here to active/deactivate two step verification.', max_length=8, null=True, verbose_name='code')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active?')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='updated time')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='two_step', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'two factor verification',
                'verbose_name_plural': 'two factor verifications',
            },
        ),
    ]
